# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rishabs', '0002_category_menuitem_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='o_phnum',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
