# Generated by Django 4.1.3 on 2022-11-23 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rishabs', '0003_ordermodel_o_phnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='o_phnum',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
