# Generated by Django 4.1.3 on 2022-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rishabs', '0003_user_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feedback',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='feedback',
            field=models.CharField(default='', max_length=100),
        ),
    ]
